[package]
categories = ["compilers", "algorithms", "multimedia", "parser-implementations"]
description = "A stack-based array programming language"
documentation = "https://docs.rs/uiua"
edition = "2021"
keywords = ["uiua", "array", "stack", "language", "apl"]
license = "MIT"
name = "uiua"
readme = "readme.md"
repository = "https://github.com/uiua-lang/uiua"
version = "0.0.22"

[dependencies]
bufreaderwriter = "0.2.4"
clap = { version = "4", optional = true, features = ["derive"] }
color-backtrace = { version = "0.6.1", optional = true }
colored = "2"
crossbeam-channel = "0.5.8"
ctrlc = { version = "3", optional = true }
dashmap = "5"
ecow = "0.2.0"
enum-iterator = "1.4.1"
gif = "0.12.0"
hodaun = { version = "0.4.1", optional = true, features = ["output", "wav"] }
hound = "3"
httparse = { version = "1.8.0", optional = true }
image = { version = "0.24.5", features = ["bmp", "gif", "ico", "jpeg", "png"] }
indexmap = { version = "2", optional = true, features = ["serde"] }
instant = "0.1.12"
lockfree = { version = "0.5.1", optional = true }
notify = { version = "6", optional = true }
once_cell = "1"
open = { version = "5", optional = true }
parking_lot = "0.12.1"
paste = "1.0.14"
rand = { version = "0.8.5", features = ["small_rng"] }
rustls = { version = "0.21.7", optional = true, default-features = false, features = [
    "tls12",
] }
serde = { version = "1", optional = true, features = ["derive"] }
serde_yaml = { version = "0.9.25", optional = true }
term_size = "1.0.0-beta1"
tinyvec = { version = "1", features = ["alloc"] }
tokio = { version = "1", optional = true, features = ["io-std", "rt"] }
tower-lsp = { version = "0.20.0", optional = true }
webpki-roots = { version = "0.25.0", optional = true }
viuer = { version = "0.7.1", optional = true }
num_cpus = "1.16.0"
rayon = "1.8.0"
regex = "1.10.2"
unicode-segmentation = "1.10"
trash = { version = "3.1.2", optional = true }
crossterm = { version = "0.22.0", optional = true, default-features = false }

[features]
audio = ["hodaun", "lockfree"]
binary = ["ctrlc", "notify", "clap", "color-backtrace", "lsp"]
debug = []
raw_mode = ["crossterm"]
default = ["binary", "terminal_image", "https", "invoke", "trash", "raw_mode"]
https = ["httparse", "rustls", "webpki-roots"]
lsp = ["tower-lsp", "tokio"]
profile = ["serde", "serde_yaml", "indexmap"]
invoke = ["open"]
terminal_image = ["viuer"]

[[bin]]
name = "uiua"

[workspace]
members = ["site"]

[profile.release]
lto = true
